title: GitHub Page Tutorial
author: Monai Thangsuphanich
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing area for trying new things in GitHub Pages.

# social links
github_username:  MonaiThang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
